name: Code junction build
on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g @angular/cli
    - run: npm cache clean --force
    - run: npm i --legacy-peer-deps
    - run: npx browserslist --update-db
    - run: npm i @ngtools/webpack --legacy-peer-deps
    - run: npm run ng build
    - run: npm test
      env:
        CI: true
