name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        node-version: '16.x'
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js '16.x'
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm install -g @angular/cli
    - run: npm i --legacy-peer-deps
    - run: npm run ng build
